#!/bin/sh

# Define color codes
CYAN='\033[0;36m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color (reset)
PREFIX="${CYAN}[QUBERSHIP]${NC}"

REPO_PATH="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_PATH" ]; then
  REPO_PATH="$PWD"
fi
LOCAL_HOOK="${REPO_PATH}/.git/hooks/commit-msg"

if [ -e "$LOCAL_HOOK" ]; then
  echo -e "${PREFIX} Local hook is defining - call it"
  sh "$LOCAL_HOOK" "$@"
  exit $?
else
  echo -e "${PREFIX} Calling CyberFerret checks for ${REPO_PATH}"
  if [ -f "${REPO_PATH}/.qubership/grand-report.json" ]; then
      if [ -n "$1" ] && grep -q "@skip_cf" "$1"; then
          echo -e "${PREFIX} ${ORANGE} Skip CyberFerret checks due to @skip_cf in commit message${NC}"
      else
          GLOBAL_HOOKS_PATH="$(git config --global core.hooksPath)"
          JAR_PATH="${GLOBAL_HOOKS_PATH}/../cyberferret-dist/cyberferret-cli.jar"
          if [ ! -f "$JAR_PATH" ]; then
              echo -e "${PREFIX} ${ORANGE} 'cyberferret-cli.jar' is not found by path ${JAR_PATH}. Use provided version or compile manually from https://github.com/exadmin/CyberFerret.${NC}"
              exit 1
          fi

          TEMP_FILES_LIST="${REPO_PATH}/.git/cf_files.list"
          # trap 'rm -f "$TEMP_FILES_LIST"' EXIT HUP INT TERM
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
              git diff HEAD --name-only > "$TEMP_FILES_LIST"
          else
              git diff --cached --name-only > "$TEMP_FILES_LIST"
          fi
          CMD="java -cp \"$JAR_PATH\" com.github.exadmin.cyberferret.CyberFerretCLI \"$REPO_PATH\" \"$TEMP_FILES_LIST\""
          echo -e "${PREFIX} ${CMD}"
          eval "$CMD"
          exit $?
      fi
  else
      echo -e "${PREFIX} ${ORANGE} File '.qubership/grand-report.json' not found in ${REPO_PATH}. Skipping CyberFerret checks.${NC}"
  fi
fi
