#!/bin/sh
#!/usr/bin/env bash

GLOBAL_HOOKS_PATH="$(git config --global core.hooksPath)"
. "$GLOBAL_HOOKS_PATH/_bootstrap"

HOOK_NAME="$(basename "$0")"
LOCAL_HOOK="./.git/hooks/$HOOK_NAME"

if [ -e "$LOCAL_HOOK" ]; then
  sh "$LOCAL_HOOK" "$@"
fi
