#!/bin/sh
#!/usr/bin/env bash

# Define color codes
CYAN='\033[0;36m'
NC='\033[0m' # No Color (reset)
PREFIX="${CYAN}[QUBERSHIP]${NC}"

# Calling global hooks in case configuration file is found by ".qubership/global-pre-commit-config.yaml" file
PROJECT_ROOT=$(git rev-parse --show-toplevel)
CFG_FILE="$PROJECT_ROOT/.pre-commit-config.yaml"
LOCAL_HOOK="$PROJECT_ROOT/.git/hooks/pre-commit"

echo -e "${PREFIX} Executing pre-commit from Global Hooks"

if [ ! -e "$LOCAL_HOOK" ] && [ -e "$CFG_FILE" ]; then
  echo -e "${PREFIX} Executing Global Hooks"
  ARGS=(hook-impl --config=.pre-commit-config.yml --hook-type=pre-commit)
  HERE="$(cd "$(dirname "$0")" && pwd)"
  ARGS+=(--hook-dir "$HERE" -- "$@")
  PYTHON=$(command -v python)

  if [ -x "$PYTHON" ]; then
      "$PYTHON" -mpre_commit "${ARGS[@]}"
      EXIT_CODE=$?
      if [ $EXIT_CODE -ne 0 ]; then
        echo -e "${PREFIX} Global hooks have returned $EXIT_CODE exit code - terminating..."
        exit $EXIT_CODE
      fi
  elif command -v pre-commit > /dev/null; then
      exec pre-commit "${ARGS[@]}"
  else
      echo '`pre-commit` not found.' 1>&2
      exit 1
  fi
elif [ -e "$LOCAL_HOOK" ]; then
  # Calling local hooks
  echo -e "${PREFIX} Executing Local Hooks"
  "$LOCAL_HOOK" "$@" || exit $? # Run local hook and exit with its status
else
  echo -e "${PREFIX} File '${CFG_FILE}' was found, skipping pre-commit call"
fi
